"""DCF docx writer — render a DcfPayload to a Word document.

Produces a standalone .docx containing the DCF narrative sections per
the spec (DCF Cover, Methodological Choices checklist, Network Diagram
placeholder, Excel reference). Follows the SYMBA Deliverable Template
V3 conventions: EU funding statement on the closing page, accessible
table head rows, project metadata.

This is a *companion* to the existing `services/reports.py` (which
produces the 8-section LCSA case report). The two can be served as
separate downloads, or future code can concatenate them into a single
combined deliverable.
"""
from __future__ import annotations

from io import BytesIO

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.shared import Pt, RGBColor

from app.engine.dcf_compose import DcfPayload

EU_FOOTER = (
    "This Project has received funding from the European Union's Horizon "
    "Research and Innovation Programme under Grant Agreement N. 101135562 — "
    "www.symbaproject.eu"
)

EU_DISCLAIMER = (
    "Funded by the European Union. Views and opinions expressed are however "
    "those of the author(s) only and do not necessarily reflect those of the "
    "European Union. The European Union cannot be held responsible for them."
)

PROJECT_TITLE = (
    "Securing local supplY chains via the development of new Methods to "
    "assess the circularity and symbiosis of the Bio-bAsed industrial "
    "ecosystem enhancing the EU competitiveness and resource independence."
)

SYMBA_BLUE = RGBColor(0x1F, 0x4E, 0x79)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_dcf_docx_bytes(payload: DcfPayload, case_title: str | None = None) -> bytes:
    """Render a DCF docx from a DcfPayload and return the bytes."""
    doc = Document()
    doc.styles["Normal"].font.size = Pt(11)

    _write_cover_block(doc, payload, case_title)
    _write_methodological_section(doc, payload)
    _write_network_section(doc, payload)
    _write_excel_reference_section(doc, payload)
    _write_eu_closing(doc)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


def _write_cover_block(doc: Document, payload: DcfPayload, case_title: str | None) -> None:
    heading = doc.add_heading(
        case_title or "SYMBA T4.6 — Data Collection File",
        level=0,
    )
    heading.runs[0].font.size = Pt(20)
    heading.runs[0].font.color.rgb = SYMBA_BLUE

    para = doc.add_paragraph()
    run = para.add_run(
        "Auto-generated by the SYMBA T4.6 Monitoring & Reporting System. "
        "This document accompanies the .xlsx inventory worksheet — see §3 of "
        "this document for the field-by-field reference."
    )
    run.italic = True

    doc.add_heading("Project metadata", level=1)
    table = doc.add_table(rows=0, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    rows = [
        ("Project", "SYMBA — Grant Agreement N. 101135562"),
        ("Project title", PROJECT_TITLE),
        ("Topic", "HORIZON-CL6-2023-CircBio-01-7 — Symbiosis in the bio-based industrial ecosystems"),
        ("Instrument", "CSA"),
        ("Task", "T4.6 — SYMBA Monitoring & Reporting System (M22–M36, ENCO lead)"),
        ("Deliverable", "D4.6 — SYMBA monitoring system"),
    ]
    for label, value in rows:
        row = table.add_row().cells
        row[0].text = label
        for run in row[0].paragraphs[0].runs:
            run.bold = True
        row[1].text = value

    doc.add_heading("DCF cover", level=1)
    table = doc.add_table(rows=0, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    rows = [
        ("Case ID", payload.case_id),
        ("Pathway", payload.pathway_id or "—"),
        ("ILCD Situation", payload.ilcd_situation or "—"),
        ("LCC Type", payload.lcc_type or "—"),
        ("S-LCA Activation State", payload.slca_activation_state or "—"),
        ("IS-01 Extended", "yes" if payload.is_01_extended else "no"),
        ("DCF schema version", payload.schema_version),
    ]
    for label, value in rows:
        cells = table.add_row().cells
        cells[0].text = label
        for run in cells[0].paragraphs[0].runs:
            run.bold = True
        cells[1].text = str(value)


def _write_methodological_section(doc: Document, payload: DcfPayload) -> None:
    doc.add_heading("§1. Methodological choices to document", level=1)

    if not payload.mandates_by_category:
        doc.add_paragraph(
            "(No procedural mandates activated for this case — anomalous; "
            "every case should activate the DEFAULT-category mandates.)"
        )
        return

    intro = doc.add_paragraph()
    intro.add_run(
        "The following procedural mandates have been activated by the pipeline "
        "for the present case. Each mandate is a methodological commitment to "
        "document in the LCSA report or its annexes; the 'Status' column lets "
        "the analyst track completion."
    )

    table = doc.add_table(rows=1, cols=5)
    table.style = "Light List Accent 1"
    head = table.rows[0].cells
    headers = ["Category", "Node ID", "Method", "Statement", "Status"]
    for i, h in enumerate(headers):
        head[i].text = h
        for run in head[i].paragraphs[0].runs:
            run.bold = True

    for category, mandates in payload.mandates_by_category.items():
        for m in mandates:
            cells = table.add_row().cells
            cells[0].text = category
            cells[1].text = m.node_id
            cells[2].text = m.method
            cells[3].text = m.statement
            cells[4].text = "pending"


def _write_network_section(doc: Document, payload: DcfPayload) -> None:
    doc.add_heading("§2. Network diagram", level=1)
    if payload.network_render_spec is None:
        doc.add_paragraph(
            "(Network diagram section is not active for this case configuration.)"
        )
        return

    doc.add_paragraph(
        "The actor/flow network diagram is rendered interactively in the SYMBA "
        "T4.6 web application's 'Data Collection' page. A static export "
        "(SVG/PNG) of the diagram is available from the application UI and "
        "can be inserted in this document after download. The diagram is "
        "derived deterministically from the Actors and Flow Matrix tabs of "
        "the companion .xlsx — actors as nodes (colored by sector), flows as "
        "directed edges (typed and weighted)."
    )


def _write_excel_reference_section(doc: Document, payload: DcfPayload) -> None:
    doc.add_heading("§3. Inventory worksheet (Excel companion)", level=1)
    doc.add_paragraph(
        "The companion .xlsx file contains the structured field reference "
        "calibrated on the pathway derived above. Fill the empty rows in each "
        "tab and return the workbook to the analyst leading the LCSA. The "
        "field-by-field activation is driven by predicates over Q1–Q7 and "
        "the derived pipeline state — see DATA_COLLECTION_FILE_v1.md §5."
    )

    doc.add_heading("Active sections", level=2)
    table = doc.add_table(rows=1, cols=3)
    table.style = "Light List Accent 1"
    head = table.rows[0].cells
    for i, h in enumerate(["Section", "Active for this case", "Active fields"]):
        head[i].text = h
        for run in head[i].paragraphs[0].runs:
            run.bold = True

    for section in payload.sections:
        if section.id in {"methodological_choices", "network_diagram"}:
            continue
        cells = table.add_row().cells
        cells[0].text = section.title_en
        cells[1].text = "yes" if section.active else "no"
        cells[2].text = str(len(section.fields)) if section.active else "—"


def _write_eu_closing(doc: Document) -> None:
    doc.add_heading("Acknowledgements & disclaimer", level=1)
    p = doc.add_paragraph()
    run = p.add_run(EU_FOOTER)
    run.italic = True

    p = doc.add_paragraph()
    run = p.add_run(EU_DISCLAIMER)
    run.italic = True
    run.font.size = Pt(9)
