"""Ad-hoc .docx report generation for arbitrary user cases.

This module powers POST /api/pipeline/report. The 12-paper batch
script in backend/scripts/generate_validation_reports.py is a
separate, more elaborate generator that uses paper-specific
bibliographic metadata; this module produces a leaner report for
user-submitted cases (no Section 1-3 paper details, kept generic).

The 8-section structure mirrors WorkingDoc §6 so end users can still
hand the file to a reviewer who knows the canonical layout.
"""
from __future__ import annotations

from collections import Counter
from io import BytesIO

from docx import Document
from docx.shared import Pt

from app.domain.enums import Q4
from app.domain.models import Q3, Case


def _format_q3(q3: Q3) -> str:
    parts: list[str] = []
    if q3.env:
        parts.append("ENV")
    if q3.eco:
        parts.append("ECO")
    if q3.soc:
        parts.append("SOC")
    return " + ".join(parts) or "(none)"


def _format_q4(q4: set[Q4]) -> str:
    return ", ".join(sorted(q.value for q in q4)) or "(none)"


def _add_kv(doc: Document, key: str, value: str) -> None:
    p = doc.add_paragraph()
    p.add_run(f"{key}: ").bold = True
    p.add_run(value)


def generate_case_report_bytes(case: Case, title: str | None = None) -> bytes:
    """Build a .docx for `case` (assumed already pipeline-run) and return
    the bytes for streaming via FastAPI Response.

    `title` is used as the document heading; defaults to a generic
    "User-submitted case" when not provided.
    """
    doc = Document()
    doc.styles["Normal"].font.size = Pt(11)

    # ----- Title -----
    heading = doc.add_heading(title or "SYMBA T4.6 — Case Report", level=0)
    heading.runs[0].font.size = Pt(20)
    doc.add_paragraph(
        "Auto-generated by the SYMBA T4.6 IS Assessment Tool. "
        "Sections 1-3 are placeholders for user-submitted cases (no "
        "bibliographic source); the engine output in sections 5/7/8 "
        "is the operational deliverable."
    ).italic = True

    # ----- Section 1 — Bibliographic placeholder -----
    doc.add_heading("1. Bibliographic reference and IS context", level=1)
    doc.add_paragraph("(User-submitted case — no bibliographic source.)")

    # ----- Section 2 — Case summary placeholder -----
    doc.add_heading("2. Case study summary", level=1)
    doc.add_paragraph(
        "Case configured by the user via the SYMBA T4.6 questionnaire. "
        "Summary text not provided by the form; users may edit this "
        "section manually after download."
    )

    # ----- Section 3 — Methodological config placeholder -----
    doc.add_heading("3. Methodological configuration adopted by the authors", level=1)
    doc.add_paragraph(
        "(Author-side configuration not applicable for user-submitted "
        "cases. Section 5 below documents the configuration the engine "
        "derived from the questionnaire answers.)"
    )

    # ----- Section 4 — Q1-Q7 compilation -----
    doc.add_heading("4. Compilation of the seven user-facing tool questions", level=1)
    _add_kv(doc, "Q1 (IS scenario archetype)",
            case.q1.value if case.q1 else "(not set)")
    _add_kv(doc, "Q2 (temporal stance)",
            case.q2.value if case.q2 else "(not set)")
    _add_kv(doc, "Q3 (sustainability dimensions)", _format_q3(case.q3))
    _add_kv(doc, "Q4 (use of results, multi-select)", _format_q4(case.q4))
    if case.flows:
        _add_kv(doc, "Q5 per-flow",
                ", ".join(f"{f.id}={f.q5.value}" for f in case.flows))
    else:
        _add_kv(doc, "Q5 per-flow", "(no flows defined)")
    _add_kv(doc, "Q6a sector",
            case.q6a.value if case.q6a else "(not set)")
    _add_kv(doc, "Q6b TRL band",
            case.q6b.value if case.q6b else "(not set)")
    _add_kv(doc, "Q7 geographic spread",
            case.q7.value if case.q7 else "(not set)")
    if case.alternative_scenarios:
        doc.add_paragraph(
            f"Q2-D alternative scenarios defined: "
            f"{len(case.alternative_scenarios)}"
        )
    if case.advanced:
        p = doc.add_paragraph()
        p.add_run("Advanced overrides: ").bold = True
        p.add_run(", ".join(f"{k}={v}" for k, v in case.advanced.items()))

    # ----- Section 5 — Tool-derived configuration -----
    doc.add_heading("5. Methodological configuration derived by the tool", level=1)
    pathway = case.pathway_id.value if case.pathway_id else "—"
    if case.is_01_extended:
        pathway = f"{pathway} (extended)"
    _add_kv(doc, "5.1 Pathway", pathway)
    _add_kv(doc, "5.2 ILCD situation",
            case.ilcd_situation.value if case.ilcd_situation else "—")
    _add_kv(doc, "5.3 LCC type",
            case.lcc_type.value if case.lcc_type else "—")
    _add_kv(doc, "5.4 S-LCA activation",
            case.slca_activation_state.value
            if case.slca_activation_state else "—")
    _add_kv(doc, "5.5 Activated nodes (count)", str(len(case.activated_nodes)))
    _add_kv(doc, "5.6 L1 BLOCK fired",
            ", ".join(case.blocked_by) if case.blocked_by else "(none)")
    _add_kv(doc, "5.7 L2 violations (count)", str(len(case.rule_violations)))
    _add_kv(doc, "5.8 L3 CDPs surfaced (count)", str(len(case.cdp_flags)))

    # 5.9 Pillar configurations
    doc.add_heading("5.9 Pillar configurations (engine-written keys)", level=2)
    pillar_pairs = [
        ("LCA", case.lca),
        ("LCC", case.lcc),
        ("S-LCA", case.slca),
        ("Report", case.report),
        ("Governance", case.governance),
        ("Methodological charter", case.methodological_charter),
        ("Review", case.review),
        ("System", case.system),
    ]
    any_written = False
    for name, pillar in pillar_pairs:
        if not pillar:
            continue
        any_written = True
        doc.add_heading(name, level=3)
        for k, v in pillar.items():
            doc.add_paragraph(f"  {k} = {v}")
    if not any_written:
        doc.add_paragraph(
            "(no pillar values written; case may be partially configured)"
        )

    # ----- Section 6 — Comparison placeholder -----
    doc.add_heading("6. Comparison: paper configuration vs tool configuration", level=1)
    doc.add_paragraph(
        "(Not applicable for user-submitted cases — no paper baseline. "
        "Reviewers may add a comparison vs an existing case study or "
        "internal practice here.)"
    )

    # ----- Section 7 — Verdict -----
    doc.add_heading("7. Validation verdict (preliminary)", level=1)
    if case.blocked_by:
        verdict = (
            "BLOCKED at L1 — case as configured triggers the listed "
            "L1 BLOCK(s); revise inputs."
        )
    elif case.rule_violations:
        verdict = (
            f"PARTIAL MATCH — pipeline runs end-to-end but reports "
            f"{len(case.rule_violations)} L2 violation(s); inspect for "
            "expert overrides or assertion adjustments."
        )
    else:
        verdict = (
            "CLEAN — pipeline runs end-to-end with zero L1/L2 "
            "violations. Tool configuration is internally consistent."
        )
    _add_kv(doc, "Preliminary verdict", verdict)

    # ----- Section 8 — Activated nodes appendix -----
    doc.add_heading("8. Appendix: full node activation list", level=1)
    grouped: dict[str, list[str]] = {}
    for nid in case.activated_nodes:
        prefix = nid.split("_")[0]
        grouped.setdefault(prefix, []).append(nid)
    counts = Counter({k: len(v) for k, v in grouped.items()})
    summary_line = ", ".join(f"{k}={n}" for k, n in counts.most_common())
    _add_kv(doc, "Counts by prefix", summary_line)
    for prefix in sorted(grouped):
        doc.add_heading(f"{prefix} ({len(grouped[prefix])})", level=2)
        doc.add_paragraph(", ".join(grouped[prefix]))

    # ----- Stream to bytes -----
    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
